### ISSUE TITLE
Add a blog (Pelican)

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/freshrss.org#10]
Actually, there is no blog! We need one!

I'm working with Pelican which is a great tool static site generator. Advantage is we will be able to store articles in a Git repository easily (Markdown format) and so having an open writing process.

I'm trying to port the actual website on Pelican so we can integrate the blog easily.

Should fix #8

**Comment by aledeg** [comment]
Nice :+1:

**Comment by marienfressinaud** [comment]
I'm working on that now. I will try to create a very basic layout for the blog but if you have some ideas, I take them!

**Comment by aledeg** [comment]
:+1: 
Do not forget to enable RSS feed with full article content.

**Comment by marienfressinaud** [comment]
Already done :)

- [Current website](http://freshrss.org/feeds/all.atom.xml)
- [Development website](http://dev.freshrss.org/feeds/all.atom.xml) (but article links are relative here instead of absolute)

**Comment by aledeg** [comment]
Good :)
But there is nothing on the page showing that there is a feed available. That's why I was confused!

**Comment by marienfressinaud** [comment]
Sure, it's a work in progress :)

**Comment by aledeg** [comment]
Do you plan to have more than one feed? for instance one blog feed and one release feed?

**Comment by marienfressinaud** [comment]
[Only (head) links are missing](http://dev.freshrss.org/feeds/release.atom.xml)

**Comment by marienfressinaud** [comment]
It's quite finished but please tell me what you think about my work before I send a PR. I have updated [dev.freshrss.org/](http://dev.freshrss.org/). So what's new?

- A new header bar to facilitate navigation
- Mention of Pelican / Python / this repository in the footer
- RSS feeds are directly accessible on the website (in the nav menu and next to the category title)
- Look and feel of the blog. I wanted something very simple but now I feel like the global theme is quite too "simple" or at least too "blue". But I will not work on a new theme anyway :p

**Comment by aledeg** [comment]
Looks good to me. The only thing, but it might be only on my machine, the icon on follow us does not render

**Comment by marienfressinaud** [comment]
Ok, it was expected but I crossed my fingers. Icons use UTF8 symbols but there is no RSS icon in them. Icon is from a [private zone of UTF8](https://en.wikipedia.org/wiki/Private_Use_Areas) so I guess it is not widely used. I will look for another solution.

**Comment by marienfressinaud** [comment]
I changes RSS and download icons to use [Icomoon font](https://icomoon.io/). It should be better now :)

**Comment by marienfressinaud** [comment]
Next steps are:

- [ ] Update README.md
- [ ] Polish CSS style and template files
- [ ] Remove temporary articles
- [ ] Write a new article to announce the blog section
- [ ] Send a pull request
- [ ] Communicate
