### ISSUE TITLE
Port to Pelican

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/freshrss.org#11]
Considering #10, I'm porting the website on Pelican. This repository will only store the content directory (pages and articles written in Markdown, RST or HTML):

- `./blog`: blog article directory
- `./extra`: favicon, robots.txt, etc.
- `./images`: images for the website
- `./pages/index.html`: the actual index page without header and footer

Documentation has to be added in order to know how to generate html from this content.

**Comment by marienfressinaud** [comment]
BTW, a new repository will need to be created to store Pelican theme and configuration.

**Comment by marienfressinaud** [comment]
Here is the result of my work for now: http://dev.freshrss.org/. It is identical (with some minor changes) but generated by Pelican :)

**Comment by marienfressinaud** [comment]
Question

For the moment I planned to host only freshrss.org content (i.e. before generation by Pelican). Should we:

- have a separated repository to host Pelican theme + instructions to build website?
- have a separated repository to host Pelican theme and put instructions in the current one (i.e. in the README)
- have a separated branch on this repository to host theme and instructions (or instructions in the README of the master branch) ?

Since theme is really specific to freshrss.org, a new branch seems ok to me. But a separated repository could improve reusability. I don't have any preference.

Any thought?

**Comment by aledeg** [comment]
I will go for 2 distinct repositories keeping in mind the HTML/CSS or Latex way of separating the content from the layout. My 2 cents.

**Comment by marienfressinaud** [comment]
Having two distinct branches is also separating content from layout :p

**Comment by aledeg** [comment]
That's true.

**Comment by marienfressinaud** [comment]
After some thoughts, I think I will create a new repository for the theme and instructions to install freshrss.org will be in the README of the current repository ;)

**Comment by marienfressinaud** [comment]
README.md is up to date in [my fork](https://github.com/marienfressinaud/freshrss.org/tree/11-port_to_pelican) and theme is available at [github.com/FreshRSS/Freshican](https://github.com/FreshRSS/Freshican).

The only line to adapt (until my PR is not merged) in the README is:

```bash
$ git clone git@github.com:FreshRSS/freshrss.org.git content
# to
$ git clone git@github.com:marienfressinaud/freshrss.org.git -b 11-port_to_pelican content
```
