### ISSUE TITLE
Fix HTTPS

### ISSUE THREAD

**Issue by NicolasKAROLAK** [FreshRSS/freshrss.org#22]
`http://url` should be replaced by `//url` to automaticaly adapt to the protocol HTTP ou HTTPS.

**Comment by NicolasKAROLAK** [comment]
I've looked at the template (<https://github.com/FreshRSS/Freshican/blob/master/templates/_header.html>) and I think that just remove `{{ SITEURL }}` variables should fix this issue, all links will become relative instead of "hard".

**Comment by marienfressinaud** [comment]
I fixed that on the website (http://freshrss.org/ and https://freshrss.org/ should work now).

Removing `{{ SITEURL }}` is not a good solution when `SITEURL = '//freshrss.org/an_additional_path'` for instance.

Please keep this ticket opened while README has not been updated with correct information.
