### ISSUE TITLE
[Article] FreshRSS supports PubSubHubbub

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/freshrss.org#28]
An article to talk about the support of PubSubhubbub in FreshRSS.

URL: http://freshrss.org/freshrss-supports-pubsubhubbub.html

You can comment the article here.

**Comment by Alkarex** [comment]
The URL does not seem to work, does it?

**Comment by marienfressinaud** [comment]
Yes that's normal, it will work when the article will be published. The dev.* URL is not supposed to be used (it's just to see the result while I'm writing ;)).

**Comment by bastienlaunay** [comment]
Voici ce que j'ai dans mes logs... Je ne comprends pas ce qui ne fonctionne pas :-(
> 2015-07-31T08:14:22+00:00	An article was discovered by pull although we use PubSubHubbub!: Feed http://www.blogger.com/feeds/XXX/posts/default GUID tag:blogger.com,1999:blog-XXX.post-XXX
> 2015-07-31T08:14:22+00:00	Set error to 1 for https://www.blogger.com/feeds/XXX/posts/default
> 2015-07-31T08:14:22+00:00	PubSubHubbub prepared for https://www.blogger.com/feeds/XXX/posts/default
> 2015-07-31T08:14:22+00:00	PubSubHubbub subscribe to https://www.blogger.com/feeds/XXX/posts/default with callback https://MONSITE/p/api/pshb.php?k=XXX: 409 Bad response code 404

**Comment by Alkarex** [comment]
@bastienlaunay : Pour le message `An article was discovered by pull although we use PubSubHubbub!`, cela n'est pas grave : cela arrive lorsque FreshRSS télécharge les nouveaux articles (par sécurité), et que tous les articles n'ont pas encore été postés par PubSubHubbub. Cela arrive surtout pour les flux avec beaucoup d'articles, ceux qui mettent quelques minutes pour poster à tous leurs abonnés, et les flux avec une mauvaise configuration (qui ne notifient pas leur hub de nouveaux articles).

Pour le second message avec un 404, c'est soit dû à une mauvaise configuration de `base_url`, soit dû à un problème de droits d'écriture dans les sous-répertoires de `./data/PubSubHubbub/*`. Vous pouvez vérifier à la main le code HTTP que vous obtenez en allant à l'adresse `https://MONSITE/p/api/pshb.php?k=XXX`. Vous pouvez aussi vérifier que le fichier `./data/PubSubHubbub/keys/XXX.txt` existe et a un code sur sa première ligne, puis que le répertoire `./data/PubSubHubbub/feeds/[code]/` existe avec un fichier `!hub.json` ainsi qu'au moins un `[utilisateur].txt`.

**Comment by Alkarex** [comment]
For all: it is a good idea to test PubSubHubbub with this test service http://push-pub.appspot.com/
