### ISSUE TITLE
Stuck on step 2

### ISSUE THREAD

**Issue by me88** [FreshRSS/freshrss.org#29]
Hello,

I try to install fresh rss on my linux server 64. I passed the step 1 (all check box are green) but I cannot pass the step 2. When I enter my username and my password I do not get any error message but I got nothing (it stays on step 2, won't go on step 3)

This is the log I get (see under).

I tried a lot of small stuffs (changing permission in var/lib/php5) but I get no result. By reading the log I do not know exactly how to solve the issue. 

Can someone give me advices ? 

Thanks

[Sat Aug 01 19:58:33.567554 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  session_start(): open(/var/lib/php5/sess_3ks3t0a7s6k1qknq0bcbp6seb1, O_RDWR) failed: Permission denied (13) in /var/www/html/rss/app/install.php on line 10, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.615400 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  Unknown: open(/var/lib/php5/sess_3ks3t0a7s6k1qknq0bcbp6seb1, O_RDWR) failed: Permission denied (13) in Unknown on line 0, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.615438 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5) in Unknown on line 0, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.641626 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  session_start(): open(/var/lib/php5/sess_3ks3t0a7s6k1qknq0bcbp6seb1, O_RDWR) failed: Permission denied (13) in /var/www/html/rss/app/install.php on line 10, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.646424 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  touch(): Unable to create file /var/www/html/rss/data/users/_/log.txt because Permission denied in /var/www/html/rss/lib/lib_rss.php on line 220, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.647311 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  Unknown: open(/var/lib/php5/sess_3ks3t0a7s6k1qknq0bcbp6seb1, O_RDWR) failed: Permission denied (13) in Unknown on line 0, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.647341 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5) in Unknown on line 0, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.668012 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  session_start(): open(/var/lib/php5/sess_3ks3t0a7s6k1qknq0bcbp6seb1, O_RDWR) failed: Permission denied (13) in /var/www/html/rss/app/install.php on line 10, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.671193 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  Unknown: open(/var/lib/php5/sess_3ks3t0a7s6k1qknq0bcbp6seb1, O_RDWR) failed: Permission denied (13) in Unknown on line 0, referer: http://localhost/rss/p/i/index.php?step=2
[Sat Aug 01 19:58:33.671222 2015] [:error] [pid 7152] [client 127.0.0.1:42677] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5) in Unknown on line 0, referer: http://localhost/rss/p/i/index.php?step=2

**Comment by Alkarex** [comment]
Hello,
Please report such problems on https://github.com/FreshRSS/FreshRSS/issues instead.
It seems to be that your PHP session configuration is wrong, since PHP (through your Web server) apparently cannot write in its session directory (apparently `/var/lib/php5/`).
For information, my `session.save_path` is `/var/lib/php5/sessions` on my Ubuntu server, as visible in `php.ini` or `phpinfo()`.

**Comment by me88** [comment]
Thanks it works now was a permission issue in the php in side

Big thanks
