### ISSUE TITLE
[Article] FreshRSS 1.6.3 is available

### ISSUE THREAD

**Issue by Trim** [FreshRSS/freshrss.org#33]
An article to announce the latest stable version.

URL: http://freshrss.org/freshrss-163-is-available.html

You can comment the article here.

**Comment by aledeg** [comment]
404 article not found

**Comment by Trim** [comment]
Yep indeed, it will be available when Pull Request #35 will be merged.

I needed to create this issue to insert the comment link in the article.

As the PR #35 need certainly more work from community / developpers, this URL will give us 404 HTTP response.
