### ISSUE TITLE
Impossible de finaliser la configuration initiale.

### ISSUE THREAD

**Issue by kxcorp** [FreshRSS/freshrss.org#37]
Bonjour,

il m'est impossible de finaliser la configuration initial, il ne prends pas le login et mot de passe et réglage de rétention des articles. Je ne peux passer cette étapes.

J'ai un reverse proxy nginx (TLS + HTTP2) avec un certificat wilcard auto-signé. "https://rss.xxxxx.com/"
en local c'est un apache2 (HTTP seulement).  "http://XXX.XXX.XXX.XXX/freshrss/"

En local cela fonctionne parfaitement.

Avez-vous déjà rencontré ce cas de figure ?

**Comment by kxcorp** [comment]
**Petite update:**

Configuration faite en local : Ok
Tentative de login depuis le reverse proxy : nOk

En vérifiant les log depuis FreshRSS : 

> Password mismatch for user=amokrane, nonce=, c=...

> 
La valeur de "c" est différente à chaque tentative.
![2017-10-05_14h06_27](https://user-images.githubusercontent.com/1993406/31226532-b92de344-a9d6-11e7-8663-06a9e147146c.png)

**Comment by Alkarex** [comment]
Bonjour,
Pourriez-vous rouvrir le ticket sur https://github.com/FreshRSS/FreshRSS/issues ?
Avez-vous regardé vos logs du serveur Web, ainsi que la console JavaScript du navigateur ?
Peut-être que vous pourriez m'envoyer l'adresse de votre serveur en message privé.

**Comment by kxcorp** [comment]
Oui sans pb :D
