### ISSUE TITLE
Image proxying ?

### ISSUE THREAD

**Issue by Gougere89** [FreshRSS/freshrss.org#41]
Hello,
First thank you for your work, it is working perfectly, even with a lot of feeds!

I would be interested in a new feature: Image proxying.

I mean, for instance on the Reading view, images are loaded from the external feed or source; which creates two "problems": 
- On HTTPS, when images are HTTP served, the FreshRSS instance is marked as "Insecure" by browsers :
![image](https://user-images.githubusercontent.com/40035013/42732988-ff74cdf8-882a-11e8-9c1e-31ca7e37401e.png)
- I am using CloudFlare and I want to cache images to make them loading faster on slower connections.

Thus, it would be great to add a setting to proxy images. 

Thank you!

**Comment by Frenzie** [comment]
Technically this is only for the website. Issues with the software itself can be reported here: https://github.com/FreshRSS/FreshRSS/issues

But in this case I think my ImageProxy extension should probably cover your use case: https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy

**Comment by Gougere89** [comment]
Hello,

Thank you for that fast answer. I am very sorry I misread and use the wrong repo. 
Thank you also for the extension, it's definitely what I need.

I close the issue.
