### ISSUE TITLE
Preview mode?

### ISSUE THREAD

**Issue by planetahuevo** [FreshRSS/freshrss.org#42]
Hi, 
I was using my FreshRSS today and was wondering if is it possible to have a "preview mode" for the list.

The idea is to be able to read the first paragraph of the content, instead of only the title. 
With so many "click bait titles" or not titles that are really bad, I end up opening each article to decide if it is interesting or not. 
It would be fantastic to have this option on the "view modes".
Thanks

**Comment by Alkarex** [comment]
Hello,
Yes, that would be nice. Please move the issue to https://github.com/FreshRSS/FreshRSS/issues
Here is for the Web site :-)

**Comment by planetahuevo** [comment]
Oh! 
Sorry for that! :D
