### ISSUE TITLE
Hope Can be proive Chinese Docments

### ISSUE THREAD

**Issue by AkarinLiu** [FreshRSS/freshrss.org#61]
I currently live in the People's Republic of China, and I would like to be able to provide Chinese documents and help guides for Chinese people.

**Comment by math-GH** [comment]
I guess the "Documentation center" is meant, that is available in English and French: https://freshrss.github.io/FreshRSS/

**Comment by Alkarex** [comment]
Indeed, documentation translation is also a possible contribution https://github.com/FreshRSS/FreshRSS/tree/edge/docs/
